### ISSUE TITLE
如果从“音频” 转文字，是不是连 ffmpeg 我也不用在本地安装了

### ISSUE THREAD

**Issue by lixingyangok** [buxuku/VideoSubtitleGenerator#1]
另外，如果项目中直接集成了 “ffmpeg.wasm” 
似乎直接通过 npm install 就把 ffmpeg 安装了，更方便，哈哈。

感谢作者分享，感谢作者开源，谢谢。

**Comment by buxuku** [comment]
是的哈。如果本身已经有音频文件了，是不需要 ffmpeg 的。ffmpeg 的主要作用就是分离视频里面的音频流。

你的思路很棒，在 node 环境里面来安装 ffmpeg， 这个我可以尝试一下。

**Comment by buxuku** [comment]
因为该项目基于 node 环境，我已经集成了 `fluent-ffmpeg` ， Thanks！

**Comment by warmhug** [comment]
我试了下 m4a 音频文件, 也能抽取出来字幕, 这里没必要只限制 mp4 文件呀?
<img width="479" alt="image" src="https://github.com/user-attachments/assets/0469775c-d770-4dec-86fe-f4749c9f07ad">

**Comment by buxuku** [comment]
> 我试了下 m4a 音频文件, 也能抽取出来字幕, 这里没必要只限制 mp4 文件呀? <img alt="image" width="479" src="https://private-user-images.githubusercontent.com/2011119/391606599-0469775c-d770-4dec-86fe-f4749c9f07ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4ODE2NDUsIm5iZiI6MTczMzg4MTM0NSwicGF0aCI6Ii8yMDExMTE5LzM5MTYwNjU5OS0wNDY5Nzc1Yy1kNzcwLTRkZWMtODZmZS1mNDc0OWM5ZjA3YWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTFUMDE0MjI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2YwZDU4NjJhM2UyMmU3OWY0Y2IzYjQxZWQ4MDBhNzlkYzM0NmMyODE2MmQ3NDgyZDI3ZDI2ODg4NWI5MDFjOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.JItZTpBYxGD_A8wBJAHBq920EN4Ljbm8bAZylSncrtE">

好提议，我将放开这里的限制。
