### ISSUE TITLE
正在安装 whisper.cpp 模型的时候出错

### ISSUE THREAD

**Issue by Cqy1995** [buxuku/VideoSubtitleGenerator#12]
curl: (28) Failed to connect to huggingface.co port 443 after 75120 ms: Couldn't connect to server

Failed to download ggml model base.en 

Please try again later or download the original Whisper model files and convert them yourself.

file:///Users/cqy_pro/Code/github/VideoSubtitleGenerator/utils.js:67
        reject(new Error(`${command} ${args.join(' ')} 进程退出，退出码 ${code}`));
               ^

Error: bash ./whisper.cpp/models/download-ggml-model.sh base.en 进程退出，退出码 1

安装失败

**Comment by Cqy1995** [comment]
使用的是全局的vpn

**Comment by buxuku** [comment]
全局VPN并不对终端生效，你需要在终端执行 
```
export https_proxy=http://127.0.0.1:7890;export http_proxy=http://127.0.0.1:7890;export all_proxy=socks5://127.0.0.1:7890
```

这里面的 7890 端口需要根据你的VPN软件来对应设置。

**Comment by buxuku** [comment]
或者可以修改项目里面 `whisper.cpp/models` 里面的 `download-ggml-model.sh` 文件，将里面的  `huggingface.co` 替换成镜像地址 `hf-mirror.com`

**Comment by Cqy1995** [comment]
好嘞，感谢🙏
