### ISSUE TITLE
博主能搞个windows版本的么？

### ISSUE THREAD

**Issue by leotsang8** [buxuku/VideoSubtitleGenerator#14]
博主能搞个windows版本的么？没有MACOS啊

**Comment by buxuku** [comment]
目前优先规划 window GUI 版本，GUI 版本项目在 https://github.com/buxuku/video-subtitle-master ， GUI 版本完成之后再看是否需要该命令行版本支持到 windows 系统

**Comment by buxuku** [comment]
当前已经支持了 window 版本，但我仅在虚拟机里面测试过，欢迎您进行测试并给予一些反馈意见。
