### ISSUE TITLE
生成的字幕为啥都是英文？

### ISSUE THREAD

**Issue by Deepsea-pineapple** [buxuku/VideoSubtitleGenerator#16]

**Comment by Deepsea-pineapple** [comment]
意思是用whisper生成字幕，生成的就是英文，还要配置翻译服务的api是吗

**Comment by buxuku** [comment]
whisper只能生成原始语言的字幕，你原来视频是英文的，它生成的就是英文的。如果要转换成其它语言的字幕，就需要通过翻译来实现。

**Comment by Deepsea-pineapple** [comment]
> whisper只能生成原始语言的字幕，你原来视频是英文的，它生成的就是英文的。如果要转换成其它语言的字幕，就需要通过翻译来实现。

但我原来的视频讲的是中文，他给我翻译并生成英文字幕了

**Comment by buxuku** [comment]
原始视频是中文的话，那你在配置文件里面把 sourceLanguage 设置成  'zh' 试试看呢。

**Comment by Deepsea-pineapple** [comment]
> 原始视频是中文的话，那你在配置文件里面把 sourceLanguage 设置成 'zh' 试试看呢。

我是直接用那个已经打包好的Video Subtitle Master程序文件
