### ISSUE TITLE
没有基础看的云里雾里

### ISSUE THREAD

**Issue by fuxin-mail** [buxuku/VideoSubtitleGenerator#7]
看介绍挺好的工具结果没看懂

**Comment by buxuku** [comment]
目前没有把它做一个客户端工具，是基于命令行运行的 node 工具。我稍微更新了一下文档，希望你能看懂。如果还有疑问，欢迎在讨论区进行讨论。

**Comment by buxuku** [comment]
很棒地，我为它做了一个客户端版本，欢迎使用体验。项目地址：https://github.com/buxuku/video-subtitle-master 
@fuxin-mail

**Comment by fuxin-mail** [comment]
> 很棒地，我为它做了一个客户端版本，欢迎使用体验。项目地址：https://github.com/buxuku/video-subtitle-master @fuxin-mail

非常好，谢谢！有点遗憾我用的是windows10没有MAC OS系统。
